backend:
  name: github
  repo: mastilnicata/mastilnicata.github.io # Path to your Github repository
  branch: work # Branch to update


#backend:
#  name: git-gateway
#local_backend: true
  # name: github
  # repo: literaturnirazgovori/literaturnirazgovori.github.io # Path to your Github repository
  # branch: work # Branch to update
  # base_url: https://warm-woodland-78106.herokuapp.com

# publish_mode: editorial_workflow
media_folder: Uploads
public_folder: Uploads

collections:
  - name: "content-blocks"
    label: "Content blocks"
    folder: "custom_collections/_content-blocks"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}"
    identifier_field: "title"
    fields:
      - { label: "Hidden", name: "hidden", widget: "boolean", default: true }
      - { label: "Title", name: "title", required: true }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Background color", name: "bg-color", default: "#B64144", widget: "color-picker", required: false }
      - { label: "Text color", name: "color", default: "white", widget: "color-picker", required: false }
      - { label: "Additionall CSS class", name: "css-class", default: "", required: false }

  - name: "animated-banners"
    label: "Animated banners"
    folder: "custom_collections/_animated-banners"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}"
    identifier_field: "title"
    fields:
      - { label: "Hidden", name: "hidden", widget: "boolean", default: true }
      - { label: "Title", name: "title", required: true }
      - { label: "Content - in rows", name: "body", widget: "markdown" }
      - label: "Background image"
        name: "background-image"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: false


  - name: "testimonial"  
    label: "Testimonials"
    folder: "custom_collections/_testimonials"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}"
    identifier_field: "name"
    fields:
      - { label: "Hidden", name: "hidden", widget: "boolean", default: true }
      - { label: "First and last name", name: "name", required: true }
      - { label: "Title", name: "title", required: true }
      - { label: "Tagline", name: "tagline" }
      - label: "Photo"
        name: "photo"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: false
      - { label: "Content", name: "body", widget: "markdown" }
      - label: "Gender icon"
        name: "genger"
        widget: "select"
        default: "Male"
        multiple: false
        options: ['Male', 'Female']

#  - name: "post" # Used in routes, e.g. /admin/collections/blog
#    label: "Post" # Used in the UI
#    folder: "_posts" # The path to the folder where the documents are stored
#    create: true # Allow users to create new documents in this collection
#    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
#    fields: # The fields for each document, usually in front matter
#      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
#      - { label: "Hidden", name: "hidden", widget: "boolean", default: true }
#      - { label: "Title", name: "title", widget: "string" }
#      - { label: "Subtitle", name: "subtitle", widget: "string" }
#      - label: "Author"
#        name: "author"
#widget: "select"
#        default: "Antonia"
#        options:
#          - { label: "Антония", value: "Antonia" }
#          - { label: "Гост-автор", value: "Guest" }
#      - { label: "Guest author name", name: "guestauthorname", widget: "string", required: false }
#      - label: "Guest author photo"
#        name: "guestauthorimage"
#        widget: "image"
#        required: false
#        media_library:
#          config:
#            multiple: false     
#      - label: "Featured Image"
#        name: "image"
#        widget: "image"
#       media_library:
#          config:
#            multiple: true
#      - { label: "Body", name: "body", widget: "markdown" }
#      - label: "Category"
#        name: "category"
#        widget: "select"
#        default: "interviews"
#        required: true
#        options:
#          - { label: "Моите книги", value: "mybooks" }
#          - { label: "Разговори", value: "talks" }
#          - { label: "Рецензии", value: "bookreviews" }
#          - { label: "Интервюта", value: "interviews" }
#          - { label: "Преводна поезия", value: "translations" }
#          - { label: "Нови книги", value: "newbooks" }
#          - { label: "Новини и събития", value: "newsevents" }
#          - { label: "Корона от книги", value: "corona" }
#      - label: "Secondary category"
#        name: "category2"
#        widget: "select"
#        default: ""
#        required: false
#        options:
#          - { label: "<none>", value: "" }
#          - { label: "Моите книги", value: "mybooks" }
#          - { label: "Разговори", value: "talks" }
#          - { label: "Рецензии", value: "bookreviews" }
#          - { label: "Интервюта", value: "interviews" }
#          - { label: "Преводна поезия", value: "translations" }
#          - { label: "Нови книги", value: "newbooks" }
#          - { label: "Новини и събития", value: "newsevents" }          
#      - {label: "Tags", name: "tags", widget: "list"}   
#      - label: "Schedule publish at"
#        name: "schedule"
#        widget: "datetime"
#        default: ""
#        format: "YYYY-MM-DD HH:mm"
#        dateFormat: "YYYY-MM-DD"
#        timeFormat: "HH:mm"
#        required: false
#      - { label: "Redirect from", name: "redirect_from", widget: "list", required: false }
